### ISSUE TITLE
'AssetManagerConfiguration' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by irshad365** [PredixDev/PredixSDKForiOS#3]
I could see few structs are inaccessible from applications using predix sdk. please add `public init(){}` to all.

[https://stackoverflow.com/questions/40249531/why-does-a-public-class-struct-in-swift-require-an-explicit-public-initializer](url) this url might help.

**Comment by jeremyosterhoudt** [comment]
Hi Irshad,

Thanks for the feedback.  We will incorporate this change to the AssetManagerConfiguration ASAP.

**Comment by irshad365** [comment]
Hi @jeremyosterhoudt , 
Thanks for the quick response. not just AssetManagerConfiguration, but i could see other public structs/class that doesn't have public init. it would be very helpful if your team could fix them all.

**Comment by jeremyosterhoudt** [comment]
Hi @irshad365,

We have identified all of the public structures that are intended to be constructed by a developer and added public initializers.  We will push a point release early next week.
