### ISSUE TITLE
Authenticate AssetManagerConfiguration

### ISSUE THREAD

**Issue by irshad365** [PredixDev/PredixSDKForiOS#5]
How do i authenticate AssetManager? `AssetManagerConfiguration` does not have any variables for it. where as i can see `uaaclient & uaasecret` in `TimeseriesManagerConfiguration` class

**Comment by irshad365** [comment]
If i run `createAssets(jsonAssets:_)` method i get `Creation of Asset Failed\nReason: Status code: 401`

and `fetchAssets(assetType:_)` method returns `Fetching Assets Failed: Status code: 401`

**Comment by jeremyosterhoudt** [comment]
Asset is intended to work with the AuthenticationManager to obtain a beater token which is used under the covers.

It works much the same way our online API works.  

If you are using the AuthenticationManager with a UAA service that is bound to Asset and are still getting a 401 please let me know.

**Comment by irshad365** [comment]
Correct me if i am wrong, you are saying i should first use authentication manager and authenticate, after that if i use asset manager, it will internally take token from some cache.

**Comment by irshad365** [comment]
Can you also please post a sample code where authentication manager and asset manager are involved if possible?

**Comment by jeremyosterhoudt** [comment]
Yes, that is correct.  You should simply need to authenticate with the AuthenticationManager and then use the AssetManager without any additional UAA interaction (this assumes the UAA instance is setup with the correct rights and zones required by the Asset Service).  

From the client side we are working on an Asset example but it is not ready.  However, the flow would be identical to the Online API guide https://github.com/PredixDev/PredixSDKForiOS/wiki/Using-Online-API-to-make-Network-Requests.  If not already configured you may need to configuring UAA to work with the Asset Service, I would recommend looking at Assets documentation for that if you need to set that up in the UAA console.

**Comment by irshad365** [comment]
I tried what you said. but i am still getting the same error. this is the code.

```
        var configuration = AuthenticationManagerConfiguration()
        configuration.baseURL = URL(string: "https://irshad.predix-uaa.run.aws-usw02-pr.ice.predix.io")
        configuration.clientId = "uaa_client"
        configuration.clientSecret = "uaa_client"
        let onlineHandler = UAAServiceAuthenticationHandler()
        onlineHandler.authenticationServiceDelegate = self
        authenticationManager = AuthenticationManager(configuration: configuration)
        authenticationManager?.authorizationHandler = UAAAuthorizationHandler()
        authenticationManager?.onlineAuthenticationHandler = onlineHandler
        
        authenticationManager?.authenticate { status in
            print(status) //  **Success: Online**
            
            var config : AssetManagerConfiguration = AssetManagerConfiguration()
            config.tenantId = "6661234b-a223-4c05-818c-44c023e9f275"
            config.URL = "https://predix-asset.run.aws-usw02-pr.ice.predix.io"
            
            let manager = AssetManager(configuration: config)
            manager.createAssets(jsonAssets: [["uri": "/locomotives/1",
                                               "type": "Diesel-electric",
                                               "model": "ES44AC",
                                               "manufacturer": "/manufacturers/GE",
                                               "engine": "/engines/v12-1",
                                               "installedOn": "01/12/2005",
                                               "coords": [
                                                "lat": 33.914605,
                                                "lng": -117.253374
                ]
                ]]) { (asset, status) in
                    print(status) // **Creation of Asset Failed\nReason: Status code: 401**
            }
        }
```

authenticationManager?.authenticate return success
my asset services (name: predix-asset) is linked to my uaa client (name: uaa_client)
<img width="794" alt="screen shot 2018-01-23 at 11 54 54 am" src="https://user-images.githubusercontent.com/12473038/35289084-590340c2-0034-11e8-8da4-ab17b47f681e.png">

but still i am getting the same 401 error message as before!!

**Comment by jeremyosterhoudt** [comment]
That all looks correct.  Let us review internally to see if it is an issue with the SDK or if there is additional help we can suggest.

**Comment by jeremyosterhoudt** [comment]
@irshad365 We are still looking into this, however, I was hoping you could help us with some additional information.  Would you be willing to report on if you can successfully retrieve data from Asset using our dev [toolkit](https://predix-toolkit.run.aws-usw02-pr.ice.predix.io/#!/asset)?

**Comment by irshad365** [comment]
Yes i can, i have tried that before, it was working properly. I will try it once more and update this comment.

**Comment by irshad365** [comment]
Guys a good news. I found the issue and solution my self through toolkit.

When i login as a client, asset (create & get) works whereas if i login as a user it doesn't.
the reason is, using UAA Dashboard, i am able to link my uaa client with asset service but there is no option explicitly tell us to link a user to asset service. 

**Solution:**
when i copied the asset's zone id(**predix-asset.zones.6661234b-a223-4c05-818c-44c023e9f275.user**) from uaa client's scope to user's scope, the problem was resolved.

**Suggestion:** 
- It is not clear anywhere in your documentation on when to login as a client and when to login as a user.
- In iOS SDK, Timeseries manager is logging as a client and asset manager is making use of user token(last part is not mentioned anywhere in the iOS docs)!! try to make it same.
- In UAA Dashboard there is option to authorize a client but no option to authorize a user !!!! (which is the main root cause of my issue). in-fact there is no such thing as scope in user management, scope is called as groups.
<img width="792" alt="screen shot 2018-01-24 at 1 30 32 pm" src="https://user-images.githubusercontent.com/12473038/35350086-cc460bd8-010a-11e8-874d-f0c93a7dca2c.png">

**Comment by irshad365** [comment]
# One more issue
when i create a asset record through iOS SDK, i get an error
`"Creation of Asset Failed\nReason: response is missing a valid json formatted data."`
but it is saved though. fetchAssets(_:) is able to retrieve the same record.

**Comment by irshad365** [comment]
Sorry to say this. how could you guys release such an unstable poorly documented tool to public. This completely takes away the trust i had in GE before starting predix.

A friendly advice. Please do revert the public release, prepare a actual document (please don't say you have realm jazzy documentation), test it properly and release.

**Comment by jeremyosterhoudt** [comment]
Ideally we want all APIs to be based on the user scope, however, TimeSeries does not support this mode of operation so there is the work around to deal with the limitation (I agree with you that it should be all one way!).

We will look into the issue for the error you reported on Asset create APIs.

**Comment by jeremyosterhoudt** [comment]
@irshad365 I've verified this is an erroneous error message in the Asset API.  I'm going to do some more testing to make sure this doesn't break other functionality but we should have a fix for the erroneous message available for consumption early next week.

**Comment by jeremyosterhoudt** [comment]
This issue should now be resolved.

As an added bonus you can now query TimeSeries data without providing separate UAA information or adding client grant to your UAA instance.  For more information please see the [TimeSeries FAQ](https://github.com/PredixDev/PredixSDKForiOS/wiki/TimeSeries-API#faq)
